spring:
  profiles: dev
server:
  port: 10008

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/homework?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=CTT
    username: root
    password: root
spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

redis:
  host: localhost
  port: 30001
  database: 3
  timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
     # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
  jedis:
    pool:
       # 最大空闲连接数
      max-idle: 500
       # 最小空闲连接数
      min-idle: 50
       # 等待可用连接的最大时间，负数为不限制
      max-wait:  -1s
       # 最大活跃连接数，负数为不限制
      max-active: -1
      password: warter@2018!^&
#开发环境开启swagger
swagger:
  enable: true